sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.venv/**,**/htmlcov/**,**/coverage/**,**/src/test/**,**/tests/**,**/*.spec.ts,**/*.test.ts,docs/JAVA_DOCS/**,docs/coverage/**
sonar.javascript.lcov.reportPaths=apps/client-ui/coverage/client-ui/lcov.info,apps/auth-service/coverage/lcov.info
sonar.python.coverage.reportPaths=apps/reporting-service/coverage/coverage.xml
sonar.coverage.jacoco.xmlReportPaths=apps/holdings-and-trade-service/target/site/jacoco/jacoco.xml,apps/order-and-sell-service/target/site/jacoco/jacoco.xml