sonar.projectKey=DuaLeapa-Project
sonar.projectName=DuaLeapa-Project
sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/htmlcov/**,**/coverage/**,**/reports/**,**/src/test/**,**/tests/**,**/e2e/**,**/*.spec.ts,**/*.test.ts,docs/JAVA_DOCS/**,docs/coverage/**
sonar.java.source=21
sonar.java.binaries=apps/holdings-and-trade-service/target/classes,apps/order-and-sell-service/target/classes
sonar.python.version=3.14
sonar.javascript.lcov.reportPaths=apps/client-ui/coverage/client-ui/lcov.info,apps/auth-service/coverage/lcov.info
sonar.python.coverage.reportPaths=apps/reporting-service/coverage/coverage.xml,reports/market-data/coverage.xml
# Written by jacoco-to-sonar-coverage.mjs; the JaCoCo importer cannot tell the two services' identical packages apart.
sonar.coverageReportPaths=apps/holdings-and-trade-service/target/site/jacoco/sonar-coverage.xml,apps/order-and-sell-service/target/site/jacoco/sonar-coverage.xml
