-- V004: the auth service no longer has a database of its own (KAN-45/KAN-143).
-- Its credentials move into this database as user_accounts, and it owns
-- refresh_tokens here.
--
-- user_accounts and users are separate tables on purpose, matching the
-- reference architecture, which lists User Accounts and Clients/Customers as
-- distinct stores. An account is what proves who someone is; a user row is who
-- they are as a customer. Each table is written by exactly one service:
--
--   user_accounts    auth service only
--   refresh_tokens   auth service only
--   users            the Java services only
--
-- Both are keyed by the same UUID, which V003 established as the token's sub
-- claim. Registration stays two steps: the auth service creates the account,
-- then the profile is created against the same id. Because they are separate
-- rows, "profile exists" is simply whether a users row is present, and the
-- users table keeps every NOT NULL it has today.
--
-- Apply after V003. Purely additive: no column is dropped, altered or relaxed.

BEGIN;

-- Credentials and access state. Columns are named to match the auth service's
-- TypeORM entity, so the service needs no mapping changes beyond the table name.
CREATE TABLE IF NOT EXISTS user_accounts (
    -- Generated by the auth service at registration and carried as the token's
    -- sub. No database default: the value is the application's to choose, the
    -- same decision V003 made for users.user_id.
    user_id               UUID PRIMARY KEY,

    email                 TEXT NOT NULL,
    password_hash         TEXT NOT NULL,

    user_role             TEXT NOT NULL DEFAULT 'TRADER'
                              CHECK (user_role IN ('ADMIN', 'TRADER')),
    account_status        TEXT NOT NULL DEFAULT 'ACTIVE'
                              CHECK (account_status IN ('ACTIVE', 'DEACTIVATED')),

    -- Lockout after repeated failures (KAN-84).
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,

    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Sign-in compares emails ignoring case, matching users_email_lower_key from
-- V003. A plain UNIQUE would let Joanna@ and joanna@ both register.
CREATE UNIQUE INDEX IF NOT EXISTS user_accounts_email_lower_key
    ON user_accounts (lower(email));

-- Revocable sessions (BR-03). Only the SHA-256 hash of a refresh token is
-- stored; the raw value goes to the client once and is never persisted, so a
-- database leak does not hand over live sessions.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- A real foreign key, impossible while this table lived in its own
    -- database. CASCADE is a backstop: accounts are deactivated rather than
    -- deleted, so it should never fire.
    user_id     UUID NOT NULL REFERENCES user_accounts(user_id) ON DELETE CASCADE,

    token_hash  TEXT NOT NULL UNIQUE,
    issued_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,

    -- Set on logout, on rotation, and when a rotated token is replayed.
    revoked_at  TIMESTAMPTZ,

    -- The token that superseded this one. Deliberately not a foreign key: it
    -- records history, and a constraint would block expiring old rows.
    replaced_by UUID
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

-- A profile cannot exist without an account behind it. NOT VALID so the
-- constraint applies instantly and governs every new row without scanning what
-- is already there: any users row predating this migration has no account, and
-- failing the migration over historical data would help nobody. Run
--   ALTER TABLE users VALIDATE CONSTRAINT users_account_fkey;
-- once those rows are reconciled or removed.
ALTER TABLE users
    ADD CONSTRAINT users_account_fkey
    FOREIGN KEY (user_id) REFERENCES user_accounts(user_id) NOT VALID;

COMMIT;

-- Follow-ups, deliberately not done here because they would break the Java
-- entities, which still map these columns:
--   users.user_role and users.account_status now duplicate user_accounts.
--     The account is the source of truth; drop them once the services read the
--     token claim instead.
--   users.email duplicates user_accounts.email. Drop it once the profile reads
--     the address from the token, or accept the copy and keep them in step.
