package app.account;

import org.junit.jupiter.api.Test;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.DriverManager;
import static org.junit.jupiter.api.Assertions.*;

class PortfolioMigrationTest {
    @Test
    void canonicalSchemaDefinesHistoryWithAccountIsolationAndCascade() throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:h2:mem:portfolio_migration;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");
             var statement = connection.createStatement()) {
            statement.execute("create table accounts(account_id integer primary key)");
            String schema = Files.readString(Path.of("../market-data/db/migrations/V001__Initialize_database.sql"));
            // Execute the canonical table and constraints, adapting only PostgreSQL's sequence syntax.
            var table = java.util.regex.Pattern.compile("CREATE TABLE portfolio_valuations \\(.*?\\);", java.util.regex.Pattern.DOTALL).matcher(schema);
            assertTrue(table.find());
            String ddl = table.group().replace("DEFAULT nextval('portfolio_valuations_valuation_id_seq'::regclass)", "GENERATED BY DEFAULT AS IDENTITY");
            statement.execute(ddl);
            var constraints = java.util.regex.Pattern.compile("ALTER TABLE portfolio_valuations ADD CONSTRAINT [^;]+;").matcher(schema);
            java.util.Set<String> applied = new java.util.HashSet<>();
            while (constraints.find()) if (applied.add(constraints.group())) statement.execute(constraints.group());
            assertTrue(schema.contains("CREATE INDEX portfolio_valuations_account_time"));
            statement.execute("insert into accounts values (1)");
            statement.execute("insert into portfolio_valuations(account_id, observed_at, portfolio_value) values (1, CURRENT_TIMESTAMP, 100.50)");
            assertThrows(java.sql.SQLException.class, () -> statement.execute(
                    "insert into portfolio_valuations(account_id, observed_at, portfolio_value) values (2, CURRENT_TIMESTAMP, 100)"));
            assertThrows(java.sql.SQLException.class, () -> statement.execute(
                    "insert into portfolio_valuations(account_id, observed_at, portfolio_value) values (1, CURRENT_TIMESTAMP, -1)"));
            statement.execute("delete from accounts where account_id=1");
            try (var result = statement.executeQuery("select count(*) from portfolio_valuations")) {
                assertTrue(result.next());
                assertEquals(0, result.getInt(1));
            }
        }
    }
}
